ALTER TABLE services
ADD COLUMN IF NOT EXISTS deposit_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE services
ADD COLUMN IF NOT EXISTS deposit_percentage DECIMAL(5,2);

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(12,2);

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS remaining_amount DECIMAL(12,2);
