UPDATE hair_styles
SET gender = 'MEN'
WHERE code IN (
    'BUZZ_CUT',
    'CREW_CUT',
    'FAUX_HAWK',
    'FRENCH_CROP',
    'LAYER_TWO_BLOCK',
    'LONG_CURLY_HAIR',
    'LONG_LAYERED_HAIR',
    'LONG_QUIFF',
    'MAN_BUN',
    'MOHAWK',
    'MULLET_NAM',
    'POMPADOUR',
    'SHORT_LAYERED_HAIR',
    'SHORT_QUIFF',
    'SIDE_PART',
    'SLICKED_BACK_UNDERCUT',
    'TOP_KNOT'
);

UPDATE hair_styles
SET gender = 'WOMEN'
WHERE code IN (
    'BUTTERFLY_CUT',
    'CURLY_LOB',
    'FRENCH_END_CURLS',
    'HIGH_LAYERED_CUT',
    'HIME_CUT',
    'HIPPIE_PERM',
    'KOREAN_VOLUME_PERM',
    'LARGE_BARREL_CURLS',
    'LAYER_WOLF_CUT',
    'LAYERED_TOMBOY_MULLET',
    'LOB_CUT',
    'LONG_LOOSE_WAVES',
    'LONG_STRAIGHT_HAIR',
    'PIXIE_CUT',
    'SHOULDER_LENGTH_FLIPPED_OUT_HAIR',
    'SHOULDER_LENGTH_LAYERED_MULLET',
    'SHOULDER_LENGTH_SHAG_CUT',
    'TOC_BOB',
    'TOC_TEM_PIXIE',
    'VICTORIA_BECKHAM_BOB'
);
